// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/contract.proto

package user

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=authId,proto3" json:"authId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByIdRequest) Reset() {
	*x = SearchByIdRequest{}
	mi := &file_user_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByIdRequest) ProtoMessage() {}

func (x *SearchByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByIdRequest.ProtoReflect.Descriptor instead.
func (*SearchByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_contract_proto_rawDescGZIP(), []int{0}
}

func (x *SearchByIdRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

type SearchByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByUsernameRequest) Reset() {
	*x = SearchByUsernameRequest{}
	mi := &file_user_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByUsernameRequest) ProtoMessage() {}

func (x *SearchByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByUsernameRequest.ProtoReflect.Descriptor instead.
func (*SearchByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_user_contract_proto_rawDescGZIP(), []int{1}
}

func (x *SearchByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Rspn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rspn) Reset() {
	*x = Rspn{}
	mi := &file_user_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rspn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rspn) ProtoMessage() {}

func (x *Rspn) ProtoReflect() protoreflect.Message {
	mi := &file_user_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rspn.ProtoReflect.Descriptor instead.
func (*Rspn) Descriptor() ([]byte, []int) {
	return file_user_contract_proto_rawDescGZIP(), []int{2}
}

func (x *Rspn) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=authId,proto3" json:"authId,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_user_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_user_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_user_contract_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *Account) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Account) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_user_contract_proto protoreflect.FileDescriptor

const file_user_contract_proto_rawDesc = "" +
	"\n" +
	"\x13user/contract.proto\x12\x06userv1\"+\n" +
	"\x11SearchByIdRequest\x12\x16\n" +
	"\x06authId\x18\x01 \x01(\x03R\x06authId\"5\n" +
	"\x17SearchByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x16\n" +
	"\x04Rspn\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x8d\x01\n" +
	"\aAccount\x12\x16\n" +
	"\x06authId\x18\x01 \x01(\x03R\x06authId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role2\xe3\x01\n" +
	"\x04User\x12.\n" +
	"\rCreateProfile\x12\x0f.userv1.Account\x1a\f.userv1.Rspn\x12+\n" +
	"\n" +
	"PutProfile\x12\x0f.userv1.Account\x1a\f.userv1.Rspn\x128\n" +
	"\n" +
	"SearchById\x12\x19.userv1.SearchByIdRequest\x1a\x0f.userv1.Account\x12D\n" +
	"\x10SearchByUsername\x12\x1f.userv1.SearchByUsernameRequest\x1a\x0f.userv1.AccountB]\n" +
	"\n" +
	"com.userv1B\rContractProtoP\x01Z\b./userv1\xa2\x02\x03UXX\xaa\x02\x06Userv1\xca\x02\x06Userv1\xe2\x02\x12Userv1\\GPBMetadata\xea\x02\x06Userv1b\x06proto3"

var (
	file_user_contract_proto_rawDescOnce sync.Once
	file_user_contract_proto_rawDescData []byte
)

func file_user_contract_proto_rawDescGZIP() []byte {
	file_user_contract_proto_rawDescOnce.Do(func() {
		file_user_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_contract_proto_rawDesc), len(file_user_contract_proto_rawDesc)))
	})
	return file_user_contract_proto_rawDescData
}

var file_user_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_contract_proto_goTypes = []any{
	(*SearchByIdRequest)(nil),       // 0: userv1.SearchByIdRequest
	(*SearchByUsernameRequest)(nil), // 1: userv1.SearchByUsernameRequest
	(*Rspn)(nil),                    // 2: userv1.Rspn
	(*Account)(nil),                 // 3: userv1.Account
}
var file_user_contract_proto_depIdxs = []int32{
	3, // 0: userv1.User.CreateProfile:input_type -> userv1.Account
	3, // 1: userv1.User.PutProfile:input_type -> userv1.Account
	0, // 2: userv1.User.SearchById:input_type -> userv1.SearchByIdRequest
	1, // 3: userv1.User.SearchByUsername:input_type -> userv1.SearchByUsernameRequest
	2, // 4: userv1.User.CreateProfile:output_type -> userv1.Rspn
	2, // 5: userv1.User.PutProfile:output_type -> userv1.Rspn
	3, // 6: userv1.User.SearchById:output_type -> userv1.Account
	3, // 7: userv1.User.SearchByUsername:output_type -> userv1.Account
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_contract_proto_init() }
func file_user_contract_proto_init() {
	if File_user_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_contract_proto_rawDesc), len(file_user_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_contract_proto_goTypes,
		DependencyIndexes: file_user_contract_proto_depIdxs,
		MessageInfos:      file_user_contract_proto_msgTypes,
	}.Build()
	File_user_contract_proto = out.File
	file_user_contract_proto_goTypes = nil
	file_user_contract_proto_depIdxs = nil
}
