// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authorization/contract.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_authorization_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccountRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateAccountRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type RemoveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAccountRequest) Reset() {
	*x = RemoveAccountRequest{}
	mi := &file_authorization_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAccountRequest) ProtoMessage() {}

func (x *RemoveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAccountRequest.ProtoReflect.Descriptor instead.
func (*RemoveAccountRequest) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAccountRequest) Reset() {
	*x = LoginAccountRequest{}
	mi := &file_authorization_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAccountRequest) ProtoMessage() {}

func (x *LoginAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAccountRequest.ProtoReflect.Descriptor instead.
func (*LoginAccountRequest) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{2}
}

func (x *LoginAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       string                 `protobuf:"bytes,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_authorization_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshRequest) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type AccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_authorization_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{4}
}

func (x *AccessRequest) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

type Tokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Access        string                 `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	Refresh       string                 `protobuf:"bytes,3,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tokens) Reset() {
	*x = Tokens{}
	mi := &file_authorization_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokens) ProtoMessage() {}

func (x *Tokens) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokens.ProtoReflect.Descriptor instead.
func (*Tokens) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{5}
}

func (x *Tokens) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tokens) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Tokens) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_authorization_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{6}
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Rspn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rspn) Reset() {
	*x = Rspn{}
	mi := &file_authorization_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rspn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rspn) ProtoMessage() {}

func (x *Rspn) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rspn.ProtoReflect.Descriptor instead.
func (*Rspn) Descriptor() ([]byte, []int) {
	return file_authorization_contract_proto_rawDescGZIP(), []int{7}
}

func (x *Rspn) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_authorization_contract_proto protoreflect.FileDescriptor

const file_authorization_contract_proto_rawDesc = "" +
	"\n" +
	"\x1cauthorization/contract.proto\x12\x0fauthorizationV1\"~\n" +
	"\x14CreateAccountRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"&\n" +
	"\x14RemoveAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x13LoginAccountRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x0eRefreshRequest\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\tR\arefresh\"'\n" +
	"\rAccessRequest\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\"J\n" +
	"\x06Tokens\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06access\x18\x02 \x01(\tR\x06access\x12\x18\n" +
	"\arefresh\x18\x03 \x01(\tR\arefresh\"/\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\x16\n" +
	"\x04Rspn\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xd9\x03\n" +
	"\rAuthorization\x12O\n" +
	"\rCreateAccount\x12%.authorizationV1.CreateAccountRequest\x1a\x17.authorizationV1.Tokens\x12M\n" +
	"\rRemoveAccount\x12%.authorizationV1.RemoveAccountRequest\x1a\x15.authorizationV1.Rspn\x12M\n" +
	"\fLoginAccount\x12$.authorizationV1.LoginAccountRequest\x1a\x17.authorizationV1.Tokens\x12J\n" +
	"\x0eRefreshSession\x12\x1f.authorizationV1.RefreshRequest\x1a\x17.authorizationV1.Tokens\x12G\n" +
	"\rLogoutSession\x12\x1f.authorizationV1.RefreshRequest\x1a\x15.authorizationV1.Rspn\x12D\n" +
	"\bUserInfo\x12\x1e.authorizationV1.AccessRequest\x1a\x18.authorizationV1.AccountB\x8a\x01\n" +
	"\x13com.authorizationV1B\rContractProtoP\x01Z\b./authv1\xa2\x02\x03AXX\xaa\x02\x0fAuthorizationV1\xca\x02\x0fAuthorizationV1\xe2\x02\x1bAuthorizationV1\\GPBMetadata\xea\x02\x0fAuthorizationV1b\x06proto3"

var (
	file_authorization_contract_proto_rawDescOnce sync.Once
	file_authorization_contract_proto_rawDescData []byte
)

func file_authorization_contract_proto_rawDescGZIP() []byte {
	file_authorization_contract_proto_rawDescOnce.Do(func() {
		file_authorization_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorization_contract_proto_rawDesc), len(file_authorization_contract_proto_rawDesc)))
	})
	return file_authorization_contract_proto_rawDescData
}

var file_authorization_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_authorization_contract_proto_goTypes = []any{
	(*CreateAccountRequest)(nil), // 0: authorizationV1.CreateAccountRequest
	(*RemoveAccountRequest)(nil), // 1: authorizationV1.RemoveAccountRequest
	(*LoginAccountRequest)(nil),  // 2: authorizationV1.LoginAccountRequest
	(*RefreshRequest)(nil),       // 3: authorizationV1.RefreshRequest
	(*AccessRequest)(nil),        // 4: authorizationV1.AccessRequest
	(*Tokens)(nil),               // 5: authorizationV1.Tokens
	(*Account)(nil),              // 6: authorizationV1.Account
	(*Rspn)(nil),                 // 7: authorizationV1.Rspn
}
var file_authorization_contract_proto_depIdxs = []int32{
	0, // 0: authorizationV1.Authorization.CreateAccount:input_type -> authorizationV1.CreateAccountRequest
	1, // 1: authorizationV1.Authorization.RemoveAccount:input_type -> authorizationV1.RemoveAccountRequest
	2, // 2: authorizationV1.Authorization.LoginAccount:input_type -> authorizationV1.LoginAccountRequest
	3, // 3: authorizationV1.Authorization.RefreshSession:input_type -> authorizationV1.RefreshRequest
	3, // 4: authorizationV1.Authorization.LogoutSession:input_type -> authorizationV1.RefreshRequest
	4, // 5: authorizationV1.Authorization.UserInfo:input_type -> authorizationV1.AccessRequest
	5, // 6: authorizationV1.Authorization.CreateAccount:output_type -> authorizationV1.Tokens
	7, // 7: authorizationV1.Authorization.RemoveAccount:output_type -> authorizationV1.Rspn
	5, // 8: authorizationV1.Authorization.LoginAccount:output_type -> authorizationV1.Tokens
	5, // 9: authorizationV1.Authorization.RefreshSession:output_type -> authorizationV1.Tokens
	7, // 10: authorizationV1.Authorization.LogoutSession:output_type -> authorizationV1.Rspn
	6, // 11: authorizationV1.Authorization.UserInfo:output_type -> authorizationV1.Account
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authorization_contract_proto_init() }
func file_authorization_contract_proto_init() {
	if File_authorization_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorization_contract_proto_rawDesc), len(file_authorization_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorization_contract_proto_goTypes,
		DependencyIndexes: file_authorization_contract_proto_depIdxs,
		MessageInfos:      file_authorization_contract_proto_msgTypes,
	}.Build()
	File_authorization_contract_proto = out.File
	file_authorization_contract_proto_goTypes = nil
	file_authorization_contract_proto_depIdxs = nil
}
